# Generated by Django 3.2.4 on 2021-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('motomodel', models.CharField(max_length=255)),
                ('engine', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enduro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('motomodel', models.CharField(max_length=255)),
                ('engine', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('motomodel', models.CharField(max_length=255)),
                ('engine', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sportbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('motomodel', models.CharField(max_length=255)),
                ('engine', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
