# Generated by Django 3.2.4 on 2021-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruiser',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enduro',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sportbike',
            name='comment',
            field=models.TextField(),
        ),
    ]
