# Generated by Django 3.2.4 on 2021-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoMarket', '0002_auto_20210613_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportbike',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
