# Generated by Django 3.2.4 on 2021-06-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotoMarket', '0009_auto_20210619_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125)),
            ],
        ),
        migrations.DeleteModel(
            name='korzina',
        ),
        migrations.AlterModelOptions(
            name='cruiser',
            options={'verbose_name_plural': 'Cruisers'},
        ),
        migrations.AlterModelOptions(
            name='enduro',
            options={'verbose_name_plural': 'Enduros'},
        ),
        migrations.AlterModelOptions(
            name='quadro',
            options={'verbose_name_plural': 'Quadros'},
        ),
        migrations.AlterModelOptions(
            name='sportbike',
            options={'verbose_name_plural': 'Sportbikes'},
        ),
        migrations.AddField(
            model_name='cruiser',
            name='is_chopper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cruiser',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='enduro',
            name='is_roadside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enduro',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quadro',
            name='max_deep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quadro',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sportbike',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sportbike',
            name='track_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enduro',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cruiser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MotoMarket.country'),
        ),
        migrations.AddField(
            model_name='enduro',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MotoMarket.country'),
        ),
        migrations.AddField(
            model_name='quadro',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MotoMarket.country'),
        ),
        migrations.AddField(
            model_name='sportbike',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MotoMarket.country'),
        ),
    ]
